#!/bin/sh
### BEGIN INIT INFO
# Provides: iptables-persist
# Required-Start: mountkernfs $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Persist iptables rules during power cycles
### END INIT INFO

CFG=/etc/iptables.persist

case "$1" in
	start)
		/sbin/iptables-restore < $CFG
		echo "iptables loaded from file"
	 ;;
	stop)
	restart)
		/sbin/iptables-save > $CFG
		echo "iptables saved to file"
	 ;;
	*)
		echo "Usage: $0 {start|stop|restart}"
	;;
esac

exit 0


